set(VOLUME_SURFACE_FILAMENT_ROOT
    "${CMAKE_CURRENT_SOURCE_DIR}/.deps/filament-main"
    CACHE PATH
    "Filament source tree prepared inside the workspace"
)

if(NOT EXISTS "${VOLUME_SURFACE_FILAMENT_ROOT}/CMakeLists.txt")
    message(FATAL_ERROR
        "Filament source was not found. Run scripts/prepare_filament.ps1 first: "
        "${VOLUME_SURFACE_FILAMENT_ROOT}"
    )
endif()

set(FILAMENT_SKIP_SAMPLES OFF CACHE BOOL "" FORCE)
set(FILAMENT_BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(FILAMENT_ENABLE_LTO OFF CACHE BOOL "" FORCE)
set(FILAMENT_SUPPORTS_VULKAN OFF CACHE BOOL "" FORCE)
set(FILAMENT_SUPPORTS_OPENGL ON CACHE BOOL "" FORCE)
set(FILAMENT_SUPPORTS_WEBGPU OFF CACHE BOOL "" FORCE)
set(FILAMENT_ENABLE_MATDBG OFF CACHE BOOL "" FORCE)
set(USE_STATIC_CRT OFF CACHE BOOL "" FORCE)

add_subdirectory(
    "${VOLUME_SURFACE_FILAMENT_ROOT}"
    "${CMAKE_CURRENT_BINARY_DIR}/filament"
    EXCLUDE_FROM_ALL
)
